spring.application.name=newspaperJSClass
spring.profiles.active=inUse

spring.datasource.url=jdbc:mysql://dam2.mysql.iesquevedo.es:3335/alvaroilzarbe_newspaper?useSSL=false
spring.datasource.username=root
spring.datasource.password=quevedo2dam
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
